<a href="https://colab.research.google.com/github/aasthagarg128/ML_Learn/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Creaing a Matrix using Numpy

In [ ]:
mat_1 = np.array([[2,3],[6,7]])
print(mat_1)

[[2 3]
 [6 7]]


In [ ]:
mat_1.shape


(2, 2)

In [ ]:
mat_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(mat_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [ ]:
mat_2.shape

(3, 3)

Creating matrices with Random Values

In [ ]:
random_mat = np.random.rand(3,3 )
print(random_mat)

[[0.52720141 0.25727046 0.88851698]
 [0.61951721 0.52787942 0.46701176]
 [0.64567004 0.08541183 0.48460404]]


Creating matrices with Random Integers

In [ ]:
# creating matrix with random integer

random_int_mat = np.random.randint(100, size=(4,5))
print(random_int_mat)

[[38 50 29 84 11]
 [78 32 52 66 82]
 [89  2 11  7 66]
 [15 44 87 83 19]]


Creating matrices with all values as 1

In [ ]:
mat_3 = np.ones((2,3))
print(mat_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
mat_3 = np.ones((6,6) , dtype=int)
print(mat_3)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


Null  Matrixor Zero Matrix

In [ ]:
null_mat = np.zeros((4,4))
print(null_mat)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
null_mat = np.zeros((6,6), dtype=int)
print(null_mat)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


Identity Matrix

In [ ]:
identity_mat  =np.eye(3,3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
iden_mat2 = np.eye(5,5)
print(iden_mat2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [ ]:
# matrixwith random values

a=np.random.randint(100, size=(4,5))
print(a)

[[88 86 61 69 43]
 [43 88 31 96 26]
 [21 72 99 54 38]
 [49 18 60  3 71]]


In [ ]:
transpose_a = np.transpose(a)
print(transpose_a)

[[88 43 21 49]
 [86 88 72 18]
 [61 31 99 60]
 [69 96 54  3]
 [43 26 38 71]]


**Matrix Addition**


Two Matrices can be added if and only ifthey have the same shape



In [ ]:
# Creating two matrices

A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])

In [ ]:
print(A)
print(B)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [ ]:
print(A.shape)
print(B.shape)

(2, 2)
(2, 2)


Adding two matrices


In [ ]:
sum = A+B
print(sum)

[[ 8 10]
 [12 14]]


In [ ]:
# creating two matrices with random values
mat1 = np.random.randint(10, size=(3,3))
mat2 = np.random.randint(20, size=(3,3))


In [ ]:
print(mat1)
print(mat2)

[[2 2 0]
 [1 9 2]
 [5 8 1]]
[[10 11 17]
 [15  8  6]
 [ 3  0 14]]


In [ ]:
print(mat1+mat2)

[[12 13 17]
 [16 17  8]
 [ 8  8 15]]


In [ ]:
sum = np.add(mat1,mat2)
print(sum)

[[12 13 17]
 [16 17  8]
 [ 8  8 15]]


In [ ]:
# creating two matrices with random values
m1 = np.random.randint(10, size=(3,3))
m2 = np.random.randint(20, size=(3,4))
sum = m1+m2

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because the shape of the matrix m1 and matrix m4 are different

**Matrix Subtraction**

In [ ]:
# Creating two matrices
A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])

diff = A-B

In [ ]:
print(diff)

[[-4 -4]
 [-4 -4]]


In [ ]:
# creating two matrices with random values
mat1 = np.random.randint(10, size=(3,3))
mat2 = np.random.randint(20, size=(3,3))


In [ ]:
print(mat1)
print(mat2)

[[8 2 3]
 [1 4 3]
 [6 6 0]]
[[17  7 18]
 [12  4 13]
 [ 1  3  1]]


In [ ]:
d = np.subtract(mat1,mat2)
print(d)

[[ -9  -5 -15]
 [-11   0 -10]
 [  5   3  -1]]


Multiplication of Matrix by a Scalar quantity

In [ ]:
x = 5
y = np.random.randint(10, size=(4,4))
print(y)
prod = x*y

[[6 3 7 1]
 [9 5 1 3]
 [6 5 5 3]
 [7 0 0 8]]


In [ ]:
print(prod)

[[30 15 35  5]
 [45 25  5 15]
 [30 25 25 15]
 [35  0  0 40]]


In [ ]:
p = np.multiply(x,y)
print(p)

[[30 15 35  5]
 [45 25  5 15]
 [30 25 25 15]
 [35  0  0 40]]


Multiplication of Two Matrices

In [ ]:
# creating two matrices with random values
mat1 = np.random.randint(10, size=(3,3))
mat2 = np.random.randint(10, size=(3,4))

In [ ]:
print(mat1)
print(mat2)

[[5 2 0]
 [2 3 5]
 [5 9 9]]
[[5 3 4 8]
 [1 4 4 8]
 [5 8 8 5]]


In [ ]:
product = np.dot(mat1,mat2)
print(product)

[[ 27  23  28  56]
 [ 38  58  60  65]
 [ 79 123 128 157]]


In [ ]:
product.shape

(3, 4)

Element wise Matrix Multiplication

In [ ]:
# creating two matrices with random values
mat1 = np.random.randint(5, size=(3,3))
mat2 = np.random.randint(5, size=(3,3))


In [ ]:
print(mat1)
print(mat2)

[[0 0 1]
 [1 1 3]
 [0 4 2]]
[[1 1 2]
 [4 1 2]
 [2 3 3]]


In [ ]:
prod = np.multiply(mat1,mat2)
print(prod)

[[ 0  0  2]
 [ 4  1  6]
 [ 0 12  6]]
