<a href="https://colab.research.google.com/github/aasthagarg128/ML_Learn/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy-Numerical  Python

Advantages of NumPy Arrays:


1.   Allows several Mathematical Operations
2.   Faster Operations



In [ ]:
import numpy as np

List VS NumPy- Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list=[i for i in range(10000)]  # create a list [0 1 2 3 ... 9999]

start_time=process_time()

python_list=[i+5 for i in python_list]   # create a list [0+5 1+5 2+5  3+5 ..... 9999+5]

end_time=process_time()

print(end_time-start_time)

0.0010794310000008522


In [ ]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()
np_array+=5
end_time=process_time()

print(end_time-start_time)

0.0010103719999996486


Numpy Array

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
# array using numpy
arr=np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# create a 1D array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape   #provides the row and column

(5,)

In [ ]:
# create a 2D array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
type(b)

[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

In [ ]:
b.shape   #No.of row=2   No of column=4

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [ ]:
#  create a numpy array of Zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#  create a numpy array of Ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#  create a numpy array of a particular value
z=np.full((3,4),9)
print(z)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [ ]:
#  create an identity matrix
i=np.eye(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#  create an array with random values
b = np.random.random((3,4))
print(b)

[[0.09287729 0.7589569  0.39384916 0.46818741]
 [0.41717831 0.32331905 0.16172423 0.40082994]
 [0.51901169 0.97688689 0.93807129 0.1745272 ]]


In [ ]:
# create a random integer values array within a specific range
c = np.random.randint(10,100,(3,5))   # range of integer--{ 10 to 100} & No. of row=3 No. of col=5
print(c)

[[13 78 62 79 18]
 [12 52 80 38 33]
 [86 69 52 85 33]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d=np.linspace(10,30,6)    # range={ 10 to 30}  &  values needed as output=6
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e=np.arange(10,30,4)    # range={ 10 to 30}  &   distance between outputs=4
print(e)

[10 14 18 22 26]


In [ ]:
# convert a list to a numpy array
list1=[10,20,20,30,30,40]

arr=np.asarray(list1)
print(arr)
type(arr)

[10 20 20 30 30 40]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[85 74 43 32 16]
 [15 19 71 18 75]
 [69 76 68 64 30]
 [37 44 60 81 30]
 [30 29 67 33 12]]


In [ ]:
# array c dimensions
c.shape

(5, 5)

In [ ]:
# number of dimensions
c.ndim

2

In [ ]:
# number of elements in an array
c.size

25

In [ ]:
# checking the data types of the values in the array
c.dtype

dtype('int64')

Mathematical Operations on a np array

In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]

print(list1+list2)   # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(1,20,(4,4))
b = np.random.randint(20,50,(4,4))

print(a)
print(b)

[[ 3 16 10 13]
 [ 8  6 19  4]
 [15 14  9  1]
 [ 3 18 11  7]]
[[31 46 21 27]
 [30 29 31 36]
 [25 42 38 42]
 [30 47 36 48]]


In [ ]:
print(a+b)
print(b-a)
print(a*b)
print(b/a)

[[34 62 31 40]
 [38 35 50 40]
 [40 56 47 43]
 [33 65 47 55]]
[[28 30 11 14]
 [22 23 12 32]
 [10 28 29 41]
 [27 29 25 41]]
[[ 93 736 210 351]
 [240 174 589 144]
 [375 588 342  42]
 [ 90 846 396 336]]
[[10.33333333  2.875       2.1         2.07692308]
 [ 3.75        4.83333333  1.63157895  9.        ]
 [ 1.66666667  3.          4.22222222 42.        ]
 [10.          2.61111111  3.27272727  6.85714286]]


In [ ]:
print(np.add(a,b))            # will give output equal to a+b
print(np.subtract(b,a))       # will give output equal to b-a
print(np.multiply(a,b))       # will give output equal to a*b
print(np.divide(b,a))         # will give output equal to b/a

[[34 62 31 40]
 [38 35 50 40]
 [40 56 47 43]
 [33 65 47 55]]
[[28 30 11 14]
 [22 23 12 32]
 [10 28 29 41]
 [27 29 25 41]]
[[ 93 736 210 351]
 [240 174 589 144]
 [375 588 342  42]
 [ 90 846 396 336]]
[[10.33333333  2.875       2.1         2.07692308]
 [ 3.75        4.83333333  1.63157895  9.        ]
 [ 1.66666667  3.          4.22222222 42.        ]
 [10.          2.61111111  3.27272727  6.85714286]]


Array  Manipulation

In [ ]:
arr=np.random.randint(1,10,(2,3))
print(arr)
arr.shape

[[5 5 2]
 [1 5 8]]


(2, 3)

In [ ]:
# Transpose
trans=np.transpose(arr)
print(trans)
trans.shape

[[5 1]
 [5 5]
 [2 8]]


(3, 2)

In [ ]:
print(arr)
trans2=arr.T
print(trans2)
trans2.shape

[[5 5 2]
 [1 5 8]]
[[5 1]
 [5 5]
 [2 8]]


(3, 2)

In [ ]:
b = arr.reshape(3,2)
print(b)
b.shape

[[5 5]
 [2 1]
 [5 8]]


(3, 2)